apiVersion: v1
kind: Secret
metadata:
  name: github-credential
  namespace: location-pipeline
stringData:
  .git-credentials: https://rh-imesquit:<github-secret>@github.com
  .gitconfig: |
    [credential "https://github.com"]
      helper = store
type: Opaque