apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-locations
  labels:
    app: app-locations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-locations
  template:
    metadata:
      labels:
        app: app-locations
    spec:
      imagePullSecrets:
        - name: quay-auth-secret
      containers:
        - name: quarkus-app
          image: quay-quay-image-registry.apps.cluster-vg29h.vg29h.sandbox1619.opentlc.com/imesquit/locations:99de5d081404e864a0195a38dc41f86588ae48b6
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: QUARKUS_HTTP_PORT
              value: "8080"
            - name: JAVA_MAX_MEM_RATIO
              value: "70"