apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: quarkus-listener
spec:
  serviceAccountName: pipeline-bot
  triggers:
    - name: github-push-events
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-webhook-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["push"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.pusher.name != 'rh-imesquit'"
      bindings:
        - ref: quarkus-github-binding
      template:
        ref: quarkus-trigger-template